config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :donations
  resources :animal_histories
  resources :vets
  resources :donor_types
  resources :addresses
  resources :animals
  root to: 'homes#index'
  get '/zip_code/:zip_code', to: 'utils#zip_code', defaults: { format: 'json' }
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :vets, inverse_of: :address
end

app/models/animal.rb
class Animal < ApplicationRecord
  mount_uploader :image, AnimalImageUploadUploader
  validates :name, presence: true, length: { maximum: 128 }
  validates :species, presence: true, length: { maximum: 128 }
  validates :breed, presence: true, length: { maximum: 68 }
  validates :note, presence: true, length: { maximum: 128 }
end

app/models/animal_history.rb
class AnimalHistory < ApplicationRecord
  belongs_to :animal
  belongs_to :vet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor_type
  belongs_to :animal, optional: true
  validates :person, presence: true, length: { maximum: 128 }
  validates :amount, presence: true, length: { maximum: 128 }
end

app/models/donor_type.rb
class DonorType < ApplicationRecord
  validates :name, presence: true, length: { maximum: 68 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, length: { maximum: 256 }
  validates :password, presence: true, length: { maximum: 8 }
end

app/models/vet.rb
class Vet < ApplicationRecord
  belongs_to :address, optional: true, inverse_of: :vets
  accepts_nested_attributes_for :address
end

app/controllers/donor_types_controller.rb
class DonorTypesController < ApplicationController
  before_action :set_donor_type, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /donor_types
  # GET /donor_types.json
  def index
    @donor_types = DonorType.all.page params[:page]
  end

  # GET /donor_types/1
  # GET /donor_types/1.json
  def show; end

  # GET /donor_types/new
  def new
    @donor_type = DonorType.new
  end

  # GET /donor_types/1/edit
  def edit; end

  # POST /donor_types
  # POST /donor_types.json
  def create
    @donor_type = DonorType.new(donor_type_params)

    respond_to do |format|
      if @donor_type.save
        format.html { redirect_to @donor_type, notice: t('messages.create.donar_type') }
        format.json { render :show, status: :created, location: @donor_type }
      else
        format.html { render :new }
        format.json { render json: @donor_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donor_types/1
  # PATCH/PUT /donor_types/1.json
  def update
    respond_to do |format|
      if @donor_type.update(donor_type_params)
        format.html { redirect_to @donor_type, notice: t('messages.update.donar_type') }
        format.json { render :show, status: :ok, location: @donor_type }
      else
        format.html { render :edit }
        format.json { render json: @donor_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donor_types/1
  # DELETE /donor_types/1.json
  def destroy
    @donor_type.destroy
    respond_to do |format|
      format.html { redirect_to donor_types_url, notice: t('messages.delete.donar_type') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_donor_type
    @donor_type = DonorType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def donor_type_params
    params.require(:donor_type).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('messages.create.user') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('messages.update.user') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('messages.delete.user') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/utils_controller.rb
class UtilsController < ApplicationController
    before_action :authenticate_user!

    def zip_code
        @address != ""
        begin
          @address = Correios::CEP::AddressFinder.get(params[:zip_code])
        rescue StandardError
          logger.debug 'Formato inválido de CEP'
        end
        respond_to do |format|
          format.json { render json: @address }
        end
    end
end
  

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /vets
  # GET /vets.json
  def index
    @vets = Vet.all.page params[:page]
  end

  # GET /vets/1
  # GET /vets/1.json
  def show; end

  # GET /vets/new
  def new
    @vet = Vet.new
    @vet.build_address
  end

  # GET /vets/1/edit
  def edit; end

  # POST /vets
  # POST /vets.json
  def create
    @vet = Vet.new(vet_params)
    respond_to do |format|
      if @vet.save
        format.html { redirect_to @vet, notice: t('messages.create.vet') }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1
  # PATCH/PUT /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to @vet, notice: t('messages.update.vet') }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1
  # DELETE /vets/1.json
  def destroy
    @vet.destroy
    respond_to do |format|
      format.html { redirect_to vets_url, notice: t('messages.delete.vet') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vet
    @vet = Vet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vet_params
    params.require(:vet).permit(:name, :fone, :crv, address_attributes: %i[id street number complement neighborhood city state zip_code])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged
    user_signed_in?
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donor_types_helper.rb
module DonorTypesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/donor_types/_form.html.erb
<%= form_for @donor_type, :html => { :class => "form-horizontal donor_type" } do |f| %>

  <% if @donor_type.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@donor_type.errors.count, "error") %> prohibited this donor_type from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @donor_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                donor_types_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= render partial: 'form', formats: [:js], locals: {time_now: Time.now} %>

app/views/donor_types/_form.js.erb
<% content_for :js do%>
    $(document).ready(function() {
        $("form[id='new_donor_type'] , form[id^='edit_donor_type_']").formValidation({
            framework: 'bootstrap',
            fields:{
                'donor_type[name]': {
                    validators: {
                        notEmpty:{
                            message: 'Por favor digite um nome.'
                        },
                        stringLength: {
                            max: 68,
                            message: 'O nome deve conter no máximo 68 caracteres.'
                        }
                    }
                }
            }
        });
    });
<% end %>

app/views/donor_types/edit.html.erb
<%- model_class = DonorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donor_types/index.html.erb
<%- model_class = DonorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @donor_types.each do |donor_type| %>
      <tr>
        <td><%= link_to donor_type.id, donor_type_path(donor_type) %></td>
        <td><%= donor_type.name %></td>
        <td><%=l donor_type.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      donor_type_path(donor_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_donor_type_path(donor_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      donor_type_path(donor_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4"><%= paginate @donor_types %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_donor_type_path,
            :class => 'btn btn-primary' %>

app/views/donor_types/new.html.erb
<%- model_class = DonorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donor_types/show.html.erb
<%- model_class = DonorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @donor_type.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              donor_types_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_donor_type_path(@donor_type), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              donor_type_path(@donor_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>