config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :donations
  resources :animal_histories
  resources :vets
  resources :donor_types
  resources :addresses
  resources :animals
  root to: 'homes#index'
  get '/zip_code/:zip_code', to: 'utils#zip_code', defaults: { format: 'json' }
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor_type
  belongs_to :animal, optional: true
  validates :person, presence: true, length: { maximum: 128 }
  validates :amount, presence: true, length: { maximum: 128 }
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all.page params[:page]
  end

  # GET /donations/1
  # GET /donations/1.json
  def show; end

  # GET /donations/new
  def new
    @donation = Donation.new
    @donations_type = DonorType.all
    @animales = Animal.all
  end

  # GET /donations/1/edit
  def edit; end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    @donations_type = DonorType.all
    @animales = Animal.all
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: t('messages.create.donation') }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: t('messages.update.donation') }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: t('messages.delete.donation') }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def donation_params
    params.require(:donation).permit(:person, :donor_type_id, :amount, :animal_id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_donation
    @donation = Donation.find(params[:id])
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for @donation, :html => { :class => "form-horizontal donation" } do |f| %>

  <% if @donation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @donation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :person, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :person, :class => 'form-control' %>
    </div>
    <%=f.error_span(:person) %>
  </div>
  <div class="form-group">
    <%= f.label :donor_type_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.select :donor_type_id, @donations_type.collect { |dt| [dt.name, dt.id]}, {include_blank: true}, { class: "form-control" }  %>
    </div>
    <%=f.error_span(:donor_type_id) %>
  </div>
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:amount) %>
  </div>
  <div class="form-group">
    <%= f.label :animal_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.select :animal_id, @animales.collect { |an| [an.name, an.id] }, {include_blank: true}, { class: "form-control"  } %>
    </div>
    <%=f.error_span(:animal_id) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                donations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= render partial: 'form', formats: [:js], locals: {time_now: Time.now} %>

app/views/donations/_form.js.erb
<% content_for :js do%>
$(document).ready(function() {
    $("form[id='new_donation'] , form[id^='edit_donation_']").formValidation({
        framework: 'bootstrap',
        fields:{
            'donation[person]': {
                validators: {
                    notEmpty: {
                        message: 'Pessoa é obrigatório.'
                    },
                    stringLength: {
                        max: 128,
                        message: 'Pessoa deve conter no máximo 128 caracteres.'
                    }
                }
            },
            'donation[donor_type_id]': {
                validators: {
                    notEmpty: {
                        message: 'Tipo de doação é obrigatório.'
                    }
                }
            },
            'donation[amount]': {
                validators: {
                    notEmpty: {
                        message: 'Quantidade é obrigatório.'
                    },
                    integer: {
                        message: 'Quantidade não é um inteiro'
                    }
                }
            },
            'donation[animal_id]': {
                validators: {
                    notEmpty: {
                        message: 'Animal é obrigatório.'
                    }
                }
            }
        }
    });

});
<% end %>

app/views/donations/edit.html.erb
<%- model_class = Donation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donations/index.html.erb
<%- model_class = Donation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:person) %></th>
      <th><%= model_class.human_attribute_name(:donor_type_id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:animal) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= link_to donation.id, donation_path(donation) %></td>
        <td><%= donation.person %></td>
        <td><%= donation.donor_type.name %></td>
        <td><%= donation.amount %></td>
        <td><%= donation.animal.name %></td>
        <td><%=l donation.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      donation_path(donation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_donation_path(donation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      donation_path(donation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7"><%= paginate @donations %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_donation_path,
            :class => 'btn btn-primary' %>

app/views/donations/new.html.erb
<%- model_class = Donation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/donations/show.html.erb
<%- model_class = Donation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:person) %>:</strong></dt>
  <dd><%= @donation.person %></dd>
  <dt><strong><%= model_class.human_attribute_name(:donor_type_id) %>:</strong></dt>
  <dd><%= @donation.donor_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @donation.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:animal_id) %>:</strong></dt>
  <dd><%= @donation.animal.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              donations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_donation_path(@donation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              donation_path(@donation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>