config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :donations
  resources :animal_histories
  resources :vets
  resources :donor_types
  resources :addresses
  resources :animals
  root to: 'homes#index'
  get '/zip_code/:zip_code', to: 'utils#zip_code', defaults: { format: 'json' }
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :vets, inverse_of: :address
end

app/models/animal.rb
class Animal < ApplicationRecord
  mount_uploader :image, AnimalImageUploadUploader
  validates :name, presence: true, length: { maximum: 128 }
  validates :species, presence: true, length: { maximum: 128 }
  validates :breed, presence: true, length: { maximum: 68 }
  validates :note, presence: true, length: { maximum: 128 }
end

app/models/animal_history.rb
class AnimalHistory < ApplicationRecord
  belongs_to :animal
  belongs_to :vet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor_type
  belongs_to :animal, optional: true
  validates :person, presence: true, length: { maximum: 128 }
  validates :amount, presence: true, length: { maximum: 128 }
end

app/models/donor_type.rb
class DonorType < ApplicationRecord
  validates :name, presence: true, length: { maximum: 68 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, length: { maximum: 256 }
  validates :password, presence: true, length: { maximum: 8 }
end

app/models/vet.rb
class Vet < ApplicationRecord
  belongs_to :address, optional: true, inverse_of: :vets
  accepts_nested_attributes_for :address
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all.page params[:page]
  end

  # GET /animals/1
  # GET /animals/1.json
  def show; end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit; end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: t('messages.create.animal') }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: t('messages.update.animal') }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: t('messages.delete.animal') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_animal
    @animal = Animal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_params
    params.require(:animal).permit(:name, :image, :species, :breed, :note)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('messages.create.user') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('messages.update.user') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('messages.delete.user') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/utils_controller.rb
class UtilsController < ApplicationController
    before_action :authenticate_user!

    def zip_code
        @address != ""
        begin
          @address = Correios::CEP::AddressFinder.get(params[:zip_code])
        rescue StandardError
          logger.debug 'Formato inválido de CEP'
        end
        respond_to do |format|
          format.json { render json: @address }
        end
    end
end
  

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /vets
  # GET /vets.json
  def index
    @vets = Vet.all.page params[:page]
  end

  # GET /vets/1
  # GET /vets/1.json
  def show; end

  # GET /vets/new
  def new
    @vet = Vet.new
    @vet.build_address
  end

  # GET /vets/1/edit
  def edit; end

  # POST /vets
  # POST /vets.json
  def create
    @vet = Vet.new(vet_params)
    respond_to do |format|
      if @vet.save
        format.html { redirect_to @vet, notice: t('messages.create.vet') }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1
  # PATCH/PUT /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to @vet, notice: t('messages.update.vet') }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1
  # DELETE /vets/1.json
  def destroy
    @vet.destroy
    respond_to do |format|
      format.html { redirect_to vets_url, notice: t('messages.delete.vet') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vet
    @vet = Vet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vet_params
    params.require(:vet).permit(:name, :fone, :crv, address_attributes: %i[id street number complement neighborhood city state zip_code])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/animal_histories_helper.rb
module AnimalHistoriesHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged
    user_signed_in?
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donor_types_helper.rb
module DonorTypesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal, :html => { :class => "form-horizontal animal" } do |f| %>

  <% if @animal.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @animal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
jjjjjjjjjjjjjjjjjjjjjjjjj
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image) %>
  </div>
  <div class="form-group">
    <%= f.label :species, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :species, :class => 'form-control' %>
    </div>
    <%=f.error_span(:species) %>
  </div>
  <div class="form-group">
    <%= f.label :breed, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :breed, :class => 'form-control' %>
    </div>
    <%=f.error_span(:breed) %>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :note, :class => 'form-control' %>
    </div>
    <%=f.error_span(:note) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                animals_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= render partial: 'form', formats: [:js], locals: {time_now: Time.now} %>

app/views/animals/_form.js.erb
<% content_for :js do%>
$(document).ready(function() {
    $("form[id='new_animal'] , form[id^='edit_animal_']").formValidation({
        framework: 'bootstrap',
        fields:{
            'animal[name]': {
                validators: {
                    notEmpty:{
                        message: 'Por favor digite um nome.'
                    },
                    stringLength: {
                        max: 128,
                        message: 'Nome deve conter no máximo 128 caracteres.'
                    }
                }
            },
            'animal[image]': {
                validators: {
                    notEmpty:{
                        message: 'Por favor, selecione uma imagem.'
                    },
                    file: {
                        extension: 'jpg,png',
                        type: 'image/jpeg,image/png',
                        maxSize: 2097152,   // 2048 * 1024
                        message: 'Escolha um arquivo no formato png ou jpg no maximo 2 Mb'
                    }
                }
            },
            'animal[species]': {
                validators: {
                    notEmpty:{
                        message: 'Por favor preencha uma espécie.'
                    },
                    stringLength: {
                        max: 128,
                        message: 'Espécie deve conter no máximo 128 caracteres.'
                    }
                }
            },
            'animal[breed]': {
                validators: {
                    notEmpty:{
                        message: 'Por favor preencha uma raça.'
                    },
                    stringLength: {
                        max: 68,
                        message: 'Raça deve conter no máximo 68 caracteres.'
                    }
                }
            },
             'animal[note]': {
                validators: {
                    notEmpty:{
                        message: 'Por favor preencha uma observação.'
                    },
                    stringLength: {
                        max: 128,
                        message: 'Observação deve conter no máximo 128 caracteres.'
                    }
                }
            }
        }
    });

});
<% end %>

app/views/animals/edit.html.erb
<%- model_class = Animal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/animals/index.html.erb
<%- model_class = Animal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:species) %></th>
      <th><%= model_class.human_attribute_name(:breed) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= link_to animal.id, animal_path(animal) %></td>
        <td><%= animal.name %></td>
        <td><%= image_tag(animal.image.thumb) if animal.image? %></td>
        <td><%= animal.species %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.note %></td>
        <td><%=l animal.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      animal_path(animal), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_animal_path(animal), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      animal_path(animal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="8"><%= paginate @animals %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_animal_path,
            :class => 'btn btn-primary' %>

app/views/animals/new.html.erb
<%- model_class = Animal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/animals/show.html.erb
<%- model_class = Animal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @animal.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd>
		<%= image_tag(@animal.image.big) if @animal.image? %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:species) %>:</strong></dt>
  <dd><%= @animal.species %></dd>
  <dt><strong><%= model_class.human_attribute_name(:breed) %>:</strong></dt>
  <dd><%= @animal.breed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @animal.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              animals_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_animal_path(@animal), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              animal_path(@animal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal animal" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
   <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= render partial: 'form', formats: [:js], locals: {time_now: Time.now} %>

app/views/users/_form.js.erb
<% content_for :js do%>
$(document).ready(function() {
    $("form[id='new_user'] , form[id^='edit_user_']").formValidation({
        framework: 'bootstrap',
        fields:{
            'user[email]': {
                validators: {
                    notEmpty: {
                        message: 'O email é obrigatório.'
                    },
                    stringLength: {
                        max: 256,
                        message: 'O email deve conter no máximo 256 caracteres.'
                    },
                    regexp: {
                        regexp: '^[^@\\s]+@([^@\\s]+\\.)+[^@\\s]+$',
                        message: 'Email inválido.'
                    }
                }
            },
            'user[password]': {
                validators: {
                    notEmpty: {
                        message: 'A senha é obrigatória.'
                    },
                    stringLength: {
                        min: 5,
                        max: 8,
                        message: 'A senha deve conter no mínimo 5 caracteres e no máximo 8 caracteres.'
                    },
                    callback: {
                        message: 'A senha deve conter no mínimo 5 caracteres e no máximo 8 caracteres.',
                        callback: function (value, validator, $field) {
                            if (value.match(/[a-z]/) || value.match(/[A-Z]/) || value.match(/[0-9]/)) {
                                return true;
                            } else {
                                return false;
                            }
                        }
                    }
                }
            }
        }
    });

});
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4"><%= paginate @users %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/vets/edit.html.erb
<%- model_class = Vet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vets/index.html.erb
<%- model_class = Vet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:fone) %></th>
      <th><%= model_class.human_attribute_name(:crv) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vets.each do |vet| %>
      <tr>
        <td><%= link_to vet.id, vet_path(vet) %></td>
        <td><%= vet.name %></td>
        <td><%= vet.fone %></td>
        <td><%= vet.crv %></td>
        <td><%=l vet.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      vet_path(vet), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vet_path(vet), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vet_path(vet),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7"><%= paginate @vets %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vet_path,
            :class => 'btn btn-primary' %>

app/views/vets/new.html.erb
<%- model_class = Vet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vets/show.html.erb
<%- model_class = Vet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @vet.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fone) %>:</strong></dt>
  <dd><%= @vet.fone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:crv) %>:</strong></dt>
  <dd><%= @vet.crv %></dd>
  <%- model_class = Address -%>
  <dt><strong><%=  model_class.human_attribute_name(:zip_code) %>:</strong></dt>
  <dd><%= @vet.address.zip_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street) %>:</strong></dt>
  <dd><%= @vet.address.street %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number)  %>:</strong></dt>
  <dd><%= @vet.address.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:complement)  %>:</strong></dt>
  <dd><%= @vet.address.complement %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhood) %>:</strong></dt>
  <dd><%= @vet.address.neighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city)  %>:</strong></dt>
  <dd><%= @vet.address.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @vet.address.state %></dd> 
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              vets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vet_path(@vet), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vet_path(@vet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>