config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :donations
  resources :animal_histories
  resources :vets
  resources :donor_types
  resources :addresses
  resources :animals
  root to: 'homes#index'
  get '/zip_code/:zip_code', to: 'utils#zip_code', defaults: { format: 'json' }
end

app/models/animal_history.rb
class AnimalHistory < ApplicationRecord
  belongs_to :animal
  belongs_to :vet
end

app/controllers/animal_histories_controller.rb
class AnimalHistoriesController < ApplicationController
  before_action :set_animal_history, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /animal_histories
  # GET /animal_histories.json
  def index
    @animal_histories = AnimalHistory.all.page params[:page]
  end

  # GET /animal_histories/1
  # GET /animal_histories/1.json
  def show; end

  # GET /animal_histories/new
  def new
    @animal_history = AnimalHistory.new
    @animals = Animal.all
    @vets = Vet.all
  end

  # GET /animal_histories/1/edit
  def edit
    @animals = Animal.all
    @vets = Vet.all
  end

  # POST /animal_histories
  # POST /animal_histories.json
  def create
    @animal_history = AnimalHistory.new(animal_history_params)

    respond_to do |format|
      if @animal_history.save
        format.html { redirect_to @animal_history, notice: t('messages.create.animal_history') }
        format.json { render :show, status: :created, location: @animal_history }
      else
        format.html { render :new }
        format.json { render json: @animal_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animal_histories/1
  # PATCH/PUT /animal_histories/1.json
  def update
    respond_to do |format|
      if @animal_history.update(animal_history_params)
        format.html { redirect_to @animal_history, notice: t('messages.update.animal_history') }
        format.json { render :show, status: :ok, location: @animal_history }
      else
        format.html { render :edit }
        format.json { render json: @animal_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animal_histories/1
  # DELETE /animal_histories/1.json
  def destroy
    @animal_history.destroy
    respond_to do |format|
      format.html { redirect_to animal_histories_url, notice: t('messages.delete.animal_history') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_animal_history
    @animal_history = AnimalHistory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_history_params
    params.require(:animal_history).permit(:date_ini, :animal_id, :vet_id, :note)
  end
end

app/helpers/animal_histories_helper.rb
module AnimalHistoriesHelper
end

app/views/animal_histories/_form.html.erb
<%= form_for @animal_history, :html => { :class => "form-horizontal animal_history" } do |f| %>

  <% if @animal_history.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@animal_history.errors.count, "error") %> prohibited this animal_history from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @animal_history.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date_ini, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date_ini, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date_ini) %>
  </div>
  <div class="form-group">
    <%= f.label :animal_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.select :animal_id, @animals.collect { |an| [an.name, an.id]}, {include_blank: true}, { class: "form-control" }  %>
    </div>
    <%=f.error_span(:animal_id) %>
  </div>
  <div class="form-group">
    <%= f.label :vet_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.select :vet_id, @vets.collect { |vt| [vt.name, vt.id]}, {include_blank: true}, { class: "form-control" }  %>
    </div>
    <%=f.error_span(:vet_id) %>
  </div>
  <div class="form-group">
    <%= f.label :note, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :note, :class => 'form-control' %>
    </div>
    <%=f.error_span(:note) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                animal_histories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
<%= render partial: 'form', formats: [:js], locals: {time_now: Time.now} %>

app/views/animal_histories/_form.js.erb
<% content_for :js do%>
$(document).ready(function() {
    $("form[id='new_animal_history'] , form[id^='edit_animal_history_']").formValidation({
        framework: 'bootstrap',
        fields:{
            'animal_history[date_ini]': {
                validators: {
                    notEmpty: {
                        message: 'Data é inicial é obrigatório.'
                    },
                    date: {
                        format: 'DD/MM/YYYY',
                        message: 'A data não está no valor válido.'
                    }
                }
            },
            'animal_history[animal_id]': {
                validators: {
                    notEmpty: {
                        message: 'Animal é obrigatório.'
                    }
                }
            },
            'animal_history[vet_id]': {
                validators: {
                    notEmpty: {
                        message: 'Veterinário é obrigatório.'
                    }
                }
            },
            'animal_history[note]': {
                validators: {
                    notEmpty: {
                        message: 'Observação é obrigatório.'
                    },
                    stringLength: {
                        max: 68,
                        message: 'Observação deve conter no máximo 68 caracteres.'
                    }
                }
            }
        }
    });

});
<% end %>

app/views/animal_histories/edit.html.erb
<%- model_class = AnimalHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/animal_histories/index.html.erb
<%- model_class = AnimalHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date_ini) %></th>
      <th><%= model_class.human_attribute_name(:animal_id) %></th>
      <th><%= model_class.human_attribute_name(:vet_id) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @animal_histories.each do |animal_history| %>
      <tr>
        <td><%= link_to animal_history.id, animal_history_path(animal_history) %></td>
        <td><%= l(animal_history.date_ini, format: :date) %></td>
        <td><%= animal_history.animal.name %></td>
        <td><%= animal_history.vet.name %></td>
        <td><%= animal_history.note %></td>
        <td><%=l animal_history.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      animal_history_path(animal_history), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_animal_history_path(animal_history), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      animal_history_path(animal_history),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="7"><%= paginate @animal_histories %></td>
    </tr>
  </tfoot>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_animal_history_path,
            :class => 'btn btn-primary' %>

app/views/animal_histories/new.html.erb
<%- model_class = AnimalHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/animal_histories/show.html.erb
<%- model_class = AnimalHistory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date_ini) %>:</strong></dt>
  <dd><%= l(@animal_history.date_ini, format: :date) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:animal_id) %>:</strong></dt>
  <dd><%= @animal_history.animal.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vet_id) %>:</strong></dt>
  <dd><%= @animal_history.vet.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @animal_history.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              animal_histories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_animal_history_path(@animal_history), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              animal_history_path(@animal_history),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>